@BASE_URL = http://localhost:8080

###
GET {{ BASE_URL }}
Content-Type: application/json

###
POST {{ BASE_URL }}/users
Content-Type: application/json

{
  "email": "asj214@naver.com",
  "name": "sjahn",
  "password": "rewq1234"
}


###
GET {{ BASE_URL }}/boards?page=1&per_page=10
Content-Type: application/json


###
POST {{ BASE_URL }}/boards
Content-Type: application/json

{
  "title": "test123123123",
  "body": "asdsadsadsadsadsadsdsad"
}

###
GET {{ BASE_URL }}/boards/1
Content-Type: application/json


###
PUT {{ BASE_URL }}/boards/1
Content-Type: application/json

{
  "title": "제목 변경 2222"
}


###
DELETE {{ BASE_URL }}/boards/2
Content-Type: application/json